// Code generated by MockGen. DO NOT EDIT.
// Source: urls.go

// Package mock_urls is a generated GoMock package.
package mock_urls

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockurlRepository is a mock of urlRepository interface.
type MockurlRepository struct {
	ctrl     *gomock.Controller
	recorder *MockurlRepositoryMockRecorder
}

// MockurlRepositoryMockRecorder is the mock recorder for MockurlRepository.
type MockurlRepositoryMockRecorder struct {
	mock *MockurlRepository
}

// NewMockurlRepository creates a new mock instance.
func NewMockurlRepository(ctrl *gomock.Controller) *MockurlRepository {
	mock := &MockurlRepository{ctrl: ctrl}
	mock.recorder = &MockurlRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockurlRepository) EXPECT() *MockurlRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockurlRepository) Add(id, url string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", id, url)
}

// Add indicates an expected call of Add.
func (mr *MockurlRepositoryMockRecorder) Add(id, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockurlRepository)(nil).Add), id, url)
}

// Get mocks base method.
func (m *MockurlRepository) Get(id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockurlRepositoryMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockurlRepository)(nil).Get), id)
}

// Mockgenerator is a mock of generator interface.
type Mockgenerator struct {
	ctrl     *gomock.Controller
	recorder *MockgeneratorMockRecorder
}

// MockgeneratorMockRecorder is the mock recorder for Mockgenerator.
type MockgeneratorMockRecorder struct {
	mock *Mockgenerator
}

// NewMockgenerator creates a new mock instance.
func NewMockgenerator(ctrl *gomock.Controller) *Mockgenerator {
	mock := &Mockgenerator{ctrl: ctrl}
	mock.recorder = &MockgeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockgenerator) EXPECT() *MockgeneratorMockRecorder {
	return m.recorder
}

// ID mocks base method.
func (m *Mockgenerator) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockgeneratorMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*Mockgenerator)(nil).ID))
}
